name: Java CI

on:
  push:
  pull_request:
  schedule:
    - cron: '0 6 * * *'

jobs:
  build:
    if: (github.event_name == 'schedule' && github.repository == 'primefaces-extensions/primefaces-integration-tests') || (github.event_name != 'schedule')
    runs-on: macos-11.0
    name: Java ${{ matrix.java }}, Profile ${{ matrix.profile }}
    strategy:
      matrix:
        java: [ 8, 11 ]
        profile: [ 'headless,firefox,theme-saga,myfaces-2.3.x', 'headless,chrome,theme-saga,myfaces-2.3.x', 'headless,chrome,csp,theme-nova,myfaces-2.3.x', 'headless,chrome,csp,theme-nova,mojarra-2.3.x' ]

    steps:
      - uses: actions/checkout@v2.3.4
      - name: Set up JDK ${{ matrix.java }}
        uses: actions/setup-java@v2
        with:
          distribution: 'adopt'
          java-version: ${{ matrix.java }}
      - name: Cache Maven packages
        uses: actions/cache@v2.1.6
        with:
          path: ~/.m2
          key: ${{ runner.os }}-m2-${{ hashFiles('**/pom.xml') }}
          restore-keys: ${{ runner.os }}-m2
      - name: Checkout PrimeFaces
        uses: actions/checkout@v2.3.4
        with:
          repository: primefaces/primefaces
          path: primefaces
      - name: Build PrimeFaces
        run: cd primefaces && mvn install && cd ..
      - name: Checkout PrimeFaces Selenium
        uses: actions/checkout@v2.3.4
        with:
          repository: primefaces-extensions/primefaces-selenium
          path: primefaces-selenium
      - name: Build PrimeFaces Selenium
        run: cd primefaces-selenium && mvn install && cd ..
      - name: Run Integration Tests
        run: |
          sudo safaridriver --enable
          mvn -B -V clean install -P${{ matrix.profile }}
