name: Java CI

#on: [push, pull_request]
on: push

jobs:
  build:
    runs-on: ubuntu-latest
    name: Java ${{ matrix.java }}
    strategy:
        matrix:
            java: [8, 11]

    steps:
      - uses: actions/checkout@v2
      - name: Set up JDK ${{ matrix.java }}
        uses: actions/setup-java@v1
        with:
          java-version: ${{ matrix.java }}
      - name: Cache Maven packages
        uses: actions/cache@v2
        with:
          path: ~/.m2
          key: ${{ runner.os }}-m2-${{ hashFiles('**/pom.xml') }}
          restore-keys: ${{ runner.os }}-m2
      - name: checkout PrimeFaces
        uses: actions/checkout@master
        with:
          repository: primefaces/primefaces
          path: primefaces
      - name: build PrimeFaces
        run: cd primefaces && mvn install && cd ..
      - name: checkout PrimeFaces Selenium
        uses: actions/checkout@master
        with:
          repository: primefaces-extensions/primefaces-selenium
          path: primefaces-selenium
      - name: build PrimeFaces Selenium
        run: cd primefaces-selenium && mvn install && cd ..
      - name: Build with Maven
        run: mvn -B -V clean install -Pheadless-mode
